version: 2
updates:
  # Update dependencies for github CI
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Update dependencies for the backend (Node.js)
  - package-ecosystem: "npm"
    directory: "/backend-server"
    schedule:
      interval: "monthly"
  
  # Update dependencies for the frontend (Vue.js)
  - package-ecosystem: "npm"
    directory: "/vuejs-client"
    schedule:
      interval: "monthly"

  # Update dependencies for the package.json file at the root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"


  # Update dependencies for Dockerfile in the backend-server directory
  - package-ecosystem: "docker"
    directory: "/backend-server"
    schedule:
      interval: "monthly" # Can be 'daily', 'weekly', or 'monthly'

  # Update dependencies for Dockerfile in the vuejs-client directory
  - package-ecosystem: "docker"
    directory: "/vuejs-client"
    schedule:
      interval: "monthly" # Can be 'daily', 'weekly', or 'monthly'
